/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Case */
        put: operations["update_case_api_cases__case_id__put"];
        post?: never;
        /** Delete Case */
        delete: operations["delete_case_api_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Dataset */
        put: operations["update_dataset_api_datasets__dataset_id__put"];
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_api_datasets__dataset_id__cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_datasets__dataset_id__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Cases */
        post: operations["import_cases_api_datasets__dataset_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_experiments_get"];
        put?: never;
        /** Run Experiment */
        post: operations["run_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_experiments__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Experiment */
        post: operations["cancel_experiment_api_experiments__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{run_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_experiments__run_id__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_api_experiments__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Detail */
        get: operations["result_detail_api_results__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{result_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Review */
        put: operations["review_api_results__result_id__review_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_cases_api_datasets__dataset_id__import_post */
        Body_import_cases_api_datasets__dataset_id__import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CompareOut */
        CompareOut: {
            /** Items */
            items: components["schemas"]["CompareRow"][];
            summary: components["schemas"]["CompareSummary"];
        };
        /** CompareRow */
        CompareRow: {
            /**
             * Change
             * @enum {string}
             */
            change: "regression" | "improvement" | "unchanged";
            /** Expected */
            expected: {
                [key: string]: unknown;
            };
            /** Input */
            input: string;
            /** New */
            new: {
                [key: string]: unknown;
            };
            /** Old */
            old: {
                [key: string]: unknown;
            } | null;
            /** Result Id */
            result_id: number;
            review: components["schemas"]["ReviewSummary"] | null;
        };
        /** CompareSummary */
        CompareSummary: {
            /** Improvements */
            improvements: number;
            /** Regressions */
            regressions: number;
            /** Total */
            total: number;
        };
        /** DashboardMetrics */
        DashboardMetrics: {
            /** Pass Rate */
            pass_rate: number;
            /** Projects */
            projects: number;
            /** Regressions */
            regressions: number;
            /** Runs */
            runs: number;
        };
        /** DashboardOut */
        DashboardOut: {
            metrics: components["schemas"]["DashboardMetrics"];
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
            /** Recent Runs */
            recent_runs: components["schemas"]["RunOut"][];
        };
        /** DatasetIn */
        DatasetIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id: number;
        };
        /** DatasetOut */
        DatasetOut: {
            /**
             * Case Count
             * @default 0
             */
            case_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Project Id */
            project_id: number;
        };
        /** DatasetPage */
        DatasetPage: {
            /** Items */
            items: components["schemas"]["DatasetOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ImportOut */
        ImportOut: {
            /** Imported */
            imported: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MetricDetails */
        MetricDetails: {
            /** Exact Match */
            exact_match: boolean;
            /** F1 */
            f1: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** Schema Valid */
            schema_valid: boolean;
        };
        /** ProjectIn */
        ProjectIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: number;
        };
        /** QualityCheck */
        QualityCheck: {
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /** QualityGate */
        QualityGate: {
            /** Checks */
            checks: components["schemas"]["QualityCheck"][];
            /** Passed */
            passed: boolean;
        };
        /** ResultOut */
        ResultOut: {
            /** Actual Output */
            actual_output: {
                [key: string]: unknown;
            };
            /** Attempt Count */
            attempt_count: number;
            /** Cost Usd */
            cost_usd: number;
            /** Expected Output */
            expected_output: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Input */
            input: string;
            /** Input Tokens */
            input_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            metric_details: components["schemas"]["MetricDetails"];
            /** Output Tokens */
            output_tokens: number;
            /** Passed */
            passed: boolean;
            /** Provider Request Id */
            provider_request_id: string | null;
            review?: components["schemas"]["ReviewSummary"] | null;
            /** Run Id */
            run_id: number;
            /** Score */
            score: number;
            /** Test Case Id */
            test_case_id: number;
        };
        /** ResultPage */
        ResultPage: {
            /** Items */
            items: components["schemas"]["ResultOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ReviewIn */
        ReviewIn: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accepted" | "rejected";
        };
        /** ReviewOut */
        ReviewOut: {
            /** Comment */
            comment: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accepted" | "rejected";
            /** Id */
            id: number;
            /** Result Id */
            result_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewSummary */
        ReviewSummary: {
            /** Comment */
            comment: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accepted" | "rejected";
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["RunOut"];
            summary: components["schemas"]["RunSummary"];
        };
        /** RunIn */
        RunIn: {
            /** Baseline Run Id */
            baseline_run_id?: number | null;
            /** Dataset Id */
            dataset_id: number;
            /**
             * Model
             * @default rules-v1
             * @enum {string}
             */
            model: "rules-v1" | "rules-v2";
            /** Name */
            name: string;
            /**
             * Prompt
             * @default Extract medications as JSON
             */
            prompt: string;
            /**
             * Prompt Version
             * @default v1
             */
            prompt_version: string;
            /**
             * Provider
             * @default deterministic
             * @constant
             */
            provider: "deterministic";
        };
        /** RunOut */
        RunOut: {
            /** Baseline Run Id */
            baseline_run_id: number | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Id */
            dataset_id: number;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Progress Completed */
            progress_completed: number;
            /** Progress Total */
            progress_total: number;
            /** Project Id */
            project_id: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Cost Usd */
            cost_usd: number;
            /** Failed */
            failed: number;
            /** Input Tokens */
            input_tokens: number;
            /** Mean F1 */
            mean_f1: number;
            /** Output Tokens */
            output_tokens: number;
            /** P50 Latency Ms */
            p50_latency_ms: number;
            /** P95 Latency Ms */
            p95_latency_ms: number;
            /** Pass Rate */
            pass_rate: number;
            /** Passed */
            passed: number;
            quality_gate: components["schemas"]["QualityGate"];
            /** Total */
            total: number;
        };
        /** TestCaseIn */
        TestCaseIn: {
            /** Expected Output */
            expected_output: {
                [key: string]: unknown;
            };
            /** Input */
            input: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** TestCaseOut */
        TestCaseOut: {
            /** Dataset Id */
            dataset_id: number;
            /** Expected Output */
            expected_output: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Input */
            input: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** TestCasePage */
        TestCasePage: {
            /** Items */
            items: components["schemas"]["TestCaseOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_case_api_cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    datasets_api_datasets_get: {
        parameters: {
            query?: {
                project_id?: number | null;
                q?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dataset_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dataset_api_datasets__dataset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_api_datasets__dataset_id__cases_get: {
        parameters: {
            query?: {
                q?: string;
                tag?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCasePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_datasets__dataset_id__cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_cases_api_datasets__dataset_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_cases_api_datasets__dataset_id__import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_experiments_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_experiments__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_experiment_api_experiments__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_experiments__run_id__compare_get: {
        parameters: {
            query: {
                baseline_id: number;
                change?: string;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_api_experiments__run_id__results_get: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_detail_api_results__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_results__result_id__review_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
